# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpatialAnalyzer
                                 A QGIS plugin
 This plugin provides data and tools for analyzing space
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-05
        copyright            : (C) 2018 by D.J Paek
        email                : dj.paek1@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SpatialAnalyzer class from file SpatialAnalyzer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .spatial_analyzer import SpatialAnalyzer
    return SpatialAnalyzer(iface)
