# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UrbanAnalyzer
                                 A QGIS plugin
 This plugin provides data and tools for analyzing urban space
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-05
        copyright            : (C) 2018 by D.J Paek
        email                : 1002jeen@daum.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UrbanAnalyzer class from file UrbanAnalyzer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .UrbanAnalyzer import UrbanAnalyzer
    return UrbanAnalyzer(iface)
