# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpatialAnalyzer
                                 A QGIS plugin
 This plugin provides data and tools for analyzing space
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-05-05
        git sha              : $Format:%H$
        copyright            : (C) 2018 by D.J Paek
        email                : dj.paek1@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.core import QgsProcessingParameterNumber

class ParameterWss(QgsProcessingParameterNumber):
    def __init__(self, name='', description='', layer_param=None, variable_options=None, default=None, optional=False):
        QgsProcessingParameterNumber.__init__(self, name, description)
        self.layer_param = layer_param
        self.variable_options = variable_options

    def clone(self):
        copy = ParameterWss(self.name(), self.description(), self.layer_param, self.variable_options)
        return copy
